#! /bin/sh



nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
$HOME/.config/polybar/launch.sh  & 


# compositing and wallpaper 

picom & 
#./polybar_autohide/polybar-autohide

#locker 
light-locker &
# feh --bg-fill ~/Pictures/i/wall/gruv.png &
xrdb merge ~/.Xresources &  # (terminal theme)

## for enabling touchpad tapping 
xinput --set-prop 'Synaptics TM3096-001' 'libinput Tapping Enabled' 1


# for night ligt 
sct 3900
## for enabling natural scrolling 
xinput --set-prop 'Synaptics TM3096-001' 'libinput Natural Scrolling Enabled' 1


 bspc monitor -d I II III IV 
# bspc monitor -d Terminal Sublime Firefox Thunar Evince

bspc config border_width         1
bspc config window_gap           2
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config top_padding 0 
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"
 
 
bspc rule -a Gimp desktop='^8' state=floating follow=on


;bspc rule -a xfce4-terminal desktop='^1'
bspc rule -a Chromium desktop='^2'
;bspc rule -a firefox desktop='^3'
;bspc rule -a brave-browser desktop='^4'
;bspc rule -a TelegramDesktop desktop='^5'

bspc rule -a vmware desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config top_padding 0

# border colors 
bspc config focused_border_color "#83a598"
bspc config normal_border_color "#454849"

