#! /bin/sh

picom -f &
nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

## for enabling touchpad tapping 
xinput --set-prop 'Synaptics TM3096-001' 'libinput Tapping Enabled' 1

## for enabling natural scrolling 
xinput --set-prop 'Synaptics TM3096-001' 'libinput Natural Scrolling Enabled' 1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.40
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Telegram desktop='^4'
bspc rule -a vmware desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
