#! /bin/sh

nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
$HOME/.config/polybar/launch.sh  & 


# for clipmenu
export CM_LAUNCHER=rofi
export CM_LAUNCHER=fzf

# compositing and wallpaper 

#./polybar_autohide/polybar-autohide
# picom --experimental-backends&
picom &
xsetroot -cursor_name left_ptr &


# feh --bg-fill ~/Pictures/i/wall/gruv.png &
xrdb merge ~/.Xresources &  # (terminal theme)

## for enabling touchpad tapping 
xinput --set-prop 'MSFT0001:00 04F3:31BE Touchpad' 'libinput Tapping Enabled' 1


# for night ligt 
sct 4500


# dotnet 
ln -s ~/net_centric_notes/ /tmp/




## for enabling natural scrolling 
xinput --set-prop 'MSFT0001:00 04F3:31BE Touchpad' 'libinput Natural Scrolling Enabled' 1


# bspc monitor eDP -d I II III IV V 
# bspc monitor HDMI-A-0 -d I II III IV V  


if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
    xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --right-of eDP
fi
bspc monitor eDP -d I II III IV V 
# bspc monitor HDMI-A-0 -d V VI VII VIII  



bspc config border_width         2
bspc config window_gap           10    
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config top_padding 0 
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"
 
 
# setting for individual app to open
bspc rule -a Zathura state=tiled
bspc rule -a KeePass2 state=floating rectangle=650x710+100+100

# border colors 
bspc config focused_border_color "#83a598"
bspc config normal_border_color "#454849"

